using Microsoft.EntityFrameworkCore;

namespace Persistances.Common;
public static class SeedProductsInDb
{
    public static void SeedProducts(ModelBuilder modelBuilder)
    {
        // Seed ProductsGroup
        modelBuilder.Entity<ProductsGroup>().HasData(
            new ProductsGroup { Id = 1, Name = "Group1",   WorkType = "Type1", IsDeleted = false, enable = true }
        );

        // Seed Productsa
        modelBuilder.Entity<Product>().HasData(
            new Product
            {
                Id = 1,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 1,
                Circulation = "1000",
                CopyCount = "100",
                PageCount = "10",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = false,
                IsCustomSize = false,
                IsCustomPage = false,
                MinCirculation = 100,
                MaxCirculation = 2000,
                MinPage = 1,
                MaxPage = 100,
                MinWidth = 10.0f,
                MaxWidth = 50.0f,
                MinLength = 20.0f,
                MaxLength = 100.0f,
                SheetDimensionId = 1,
                FileExtension = ".pdf",
                IsCmyk = true,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 2,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 2,
                Circulation = "1500",
                CopyCount = "150",
                PageCount = "20",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = false,
                IsCustomSize = true,
                IsCustomPage = false,
                MinCirculation = 200,
                MaxCirculation = 2500,
                MinPage = 1,
                MaxPage = 150,
                MinWidth = 15.0f,
                MaxWidth = 60.0f,
                MinLength = 25.0f,
                MaxLength = 120.0f,
                SheetDimensionId = 1,
                FileExtension = ".jpg",
                IsCmyk = false,
                CutMargin = 0.5f,
                PrintMargin = 1.5f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 3,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 1,
                Circulation = "2000",
                CopyCount = "200",
                PageCount = "30",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = true,
                IsCustomSize = false,
                IsCustomPage = false,
                MinCirculation = 300,
                MaxCirculation = 3000,
                MinPage = 1,
                MaxPage = 200,
                MinWidth = 20.0f,
                MaxWidth = 70.0f,
                MinLength = 30.0f,
                MaxLength = 130.0f,
                SheetDimensionId = 1,
                FileExtension = ".pdf",
                IsCmyk = true,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 4,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 1,
                Circulation = "2500",
                CopyCount = "250",
                PageCount = "40",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = false,
                IsCustomSize = true,
                IsCustomPage = false,
                MinCirculation = 400,
                MaxCirculation = 4000,
                MinPage = 1,
                MaxPage = 300,
                MinWidth = 25.0f,
                MaxWidth = 75.0f,
                MinLength = 35.0f,
                MaxLength = 140.0f,
                SheetDimensionId = 1,
                FileExtension = ".png",
                IsCmyk = false,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 5,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 2,
                Circulation = "3000",
                CopyCount = "300",
                PageCount = "50",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = true,
                IsCustomSize = false,
                IsCustomPage = false,
                MinCirculation = 500,
                MaxCirculation = 5000,
                MinPage = 1,
                MaxPage = 400,
                MinWidth = 30.0f,
                MaxWidth = 80.0f,
                MinLength = 40.0f,
                MaxLength = 150.0f,
                SheetDimensionId = 1,
                FileExtension = ".tif",
                IsCmyk = true,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 6,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 1,
                Circulation = "3500",
                CopyCount = "350",
                PageCount = "60",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = false,
                IsCustomSize = true,
                IsCustomPage = false,
                MinCirculation = 600,
                MaxCirculation = 6000,
                MinPage = 1,
                MaxPage = 500,
                MinWidth = 35.0f,
                MaxWidth = 90.0f,
                MinLength = 45.0f,
                MaxLength = 160.0f,
                SheetDimensionId = 1,
                FileExtension = ".pdf",
                IsCmyk = false,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 7,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 2,
                Circulation = "4000",
                CopyCount = "400",
                PageCount = "70",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = true,
                IsCustomSize = false,
                IsCustomPage = false,
                MinCirculation = 700,
                MaxCirculation = 7000,
                MinPage = 1,
                MaxPage = 600,
                MinWidth = 40.0f,
                MaxWidth = 100.0f,
                MinLength = 50.0f,
                MaxLength = 170.0f,
                SheetDimensionId = 1,
                FileExtension = ".jpg",
                IsCmyk = true,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 8,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 1,
                Circulation = "4500",
                CopyCount = "450",
                PageCount = "80",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = false,
                IsCustomSize = true,
                IsCustomPage = false,
                MinCirculation = 800,
                MaxCirculation = 8000,
                MinPage = 1,
                MaxPage = 700,
                MinWidth = 45.0f,
                MaxWidth = 110.0f,
                MinLength = 55.0f,
                MaxLength = 180.0f,
                SheetDimensionId = 1,
                FileExtension = ".gif",
                IsCmyk = false,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 9,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 2,
                Circulation = "5000",
                CopyCount = "500",
                PageCount = "90",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = true,
                IsCustomSize = false,
                IsCustomPage = false,
                MinCirculation = 900,
                MaxCirculation = 9000,
                MinPage = 1,
                MaxPage = 800,
                MinWidth = 50.0f,
                MaxWidth = 120.0f,
                MinLength = 60.0f,
                MaxLength = 190.0f,
                SheetDimensionId = 1,
                FileExtension = ".pdf",
                IsCmyk = true,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            },
            new Product
            {
                Id = 10,
                ProductGroupId = 1,
                WorkTypeId = 1,
                ProductType = 1,
                Circulation = "5500",
                CopyCount = "550",
                PageCount = "100",
                PrintSide = 1,
                IsDelete = false,
                IsCalculatePrice = true,
                IsCustomCirculation = false,
                IsCustomSize = true,
                IsCustomPage = false,
                MinCirculation = 1000,
                MaxCirculation = 10000,
                MinPage = 1,
                MaxPage = 900,
                MinWidth = 55.0f,
                MaxWidth = 130.0f,
                MinLength = 65.0f,
                MaxLength = 200.0f,
                SheetDimensionId = 1,
                FileExtension = ".tiff",
                IsCmyk = false,
                CutMargin = 0.5f,
                PrintMargin = 1.0f,
                IsCheckFile = true
            }
        );

        // Optionally, you can also seed other related entities like ProductJeld, ProductAdt, etc.
    }
}

